### ISSUE TITLE
How to test the models on our videos/real time ?

### ISSUE THREAD

**Issue by vismayaps** [KaiyangZhou/deep-person-reid#12]
Hi,
I was able to run the testing command without any error, but how to visualise the tested data ? How to see the performance on our own videos or real time ? Where can I find the test results of market1501 tested with resnet50 model ?
Any help would be appreciated !!
Thanks.

**Comment by KaiyangZhou** [comment]
Hello,
To visualize the test data, you would need to output the ranked order for each query.

It would require some engineering work to test on your own videos because you need to 1) use person detector to detect person bounding boxes and 2) use tracker to track detected persons. Based on the trajectories, you can either pick up one image (image reid) or a sequence of images (video reid) for matching.

The test results, i.e. CMC and mAP, are printed on the screen at the end of training.

This repo is mainly developed for academic use, so please do not ask industry-related questions.
