### ISSUE TITLE
How to call with tensorflow

### ISSUE THREAD

**Issue by ciwei123** [KaiyangZhou/deep-person-reid#122]
@KaiyangZhou Hi, I want to use this reid model in tensorflow frame. Because I want to combine this reid frame with SSD . SSD is tensorflow frame. How should I do? Thank you very much!!!

**Comment by KaiyangZhou** [comment]
Hi,

> SSD is tensorflow frame.

What does this mean? I assume you are asking how to integrate this code to the tensorflow framework. You need to deal with the tensor type problem because pytorch uses `torch.tensor` while tf uses `tf.tensor`. It's not straightforward as I can see, so I would recommend you use the same framework for your application. How about using this pytorch-ssd implementation https://github.com/qfgaohao/pytorch-ssd?

As building the application-oriented reid system is beyond the scope of this project, I won't answer questions regarding this. Sorry.
