### ISSUE TITLE
Incredibly high map, are there potential bugs in evaluation codes?

### ISSUE THREAD

**Issue by WannaSeaU** [KaiyangZhou/deep-person-reid#170]
I have trained a video-based model which has a outstanding performance:
My training script is:
```shell
python main.py --app video\
               -s    dukemtmcvidreid\
               -t    dukemtmcvidreid\
               -j 8 \
               --height 256 \
               --width 128 \
               --optim amsgrad \
               --label-smooth \
               --lr 0.0003 \
               --max-epoch 60 \
               --stepsize 20 40 \
               --fixbase-epoch 10 \
               --open-layers classifier \
               --save-dir log/pcb-Duke-Video-combined-freeze\
               --root ../../dataset/DukeMTMC-VideoReID\
               --batch-size 16\
               --gpu-devices 0,1\
               -a pcb_p6\
               --train-sampler RandomIdentitySampler\
               --loss triplet     
```
And the performance imformation logged :
```
##### Evaluating dukemtmcvidreid (source) #####
Extracting features from query set ...
Done, obtained 702-by-12288 matrix
Extracting features from gallery set ...
Done, obtained 2636-by-12288 matrix
Speed: 0.0620 sec/batch
Computing CMC and mAP ...
** Results **
mAP: 90.0%
CMC curve
Rank-1  : 89.3%
Rank-5  : 97.4%
Rank-10 : 98.9%
Rank-20 : 99.3%
```
It's almost **SOTA**, I'm wondering whether there could be some bugs in evaluation.

Also, is it regular that mAP is higher than rank-1?

**Comment by KaiyangZhou** [comment]
It's not surprising that a sota reid model gets a good performance on dukemtmcvidreid, which is an easy benchmark because the images are hand-cropped and well-aligned. A harder dataset based on duke is this one https://github.com/liminxian/DukeMTMC-SI-Tracklet where the images are obtained using detectors. Unfortunately, all duke-related data is unavailable.

Regarding the evaluation, [the code](https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/metrics/rank.py#L135) follows the guideline of calculating [mAP for retrieval](https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Average_precision) so the result should be normal. I do not spot any error in the code. Should you find any error in the code, please let me know.

A related discussion is here https://github.com/KaiyangZhou/deep-person-reid/issues/114#issuecomment-471376218
