### ISSUE TITLE
Train on multiple object classes? (Cars, pedestrians etc.)

### ISSUE THREAD

**Issue by tiberium24** [KaiyangZhou/deep-person-reid#292]
Hello,

Is it possible to train the network simultaneously on different object classes such as cars pedestrians bicycles etc? The goal is to track all of them and distinguish also among different people cars etc.

**Comment by KaiyangZhou** [comment]
that's doable, try training the network using classification

**Comment by tiberium24** [comment]
thanks for your reply. could you please instruct me a bit further on how to do it? I can see that we can write our own dataset classes. Should I combine those pedestrian datasets with some vehicle datasets and expect it to work?

**Comment by KaiyangZhou** [comment]
sorry for this late reply as I have been super busy

I assume you have solved the (engineering) problem, but I would still like to point out that your problem is more than just a simple object classification problem but involves both generic object recognition and fine-grained classification. Therefore, I would suggest you design a new model architecture (based on OSNet) and/or some training algorithms (like multi-task learning) that best suit your task. As I am not familiar with your task requirements so could not provide further advice.
