### ISSUE TITLE
训练的时候为什么rank1的精度会下降？

### ISSUE THREAD

**Issue by guanyonglai** [KaiyangZhou/deep-person-reid#338]
epoch-2:  Rank-1  : 21.2%
epoch-50: Rank-1  : 77.4%
epoch-100:Rank-1  : 73.7%
epoch-150:Rank-1  : 82.8%
epoch-200:Rank-1  : 85.8%
epoch-250:Rank-1  : 88.6%

**Comment by KaiyangZhou** [comment]
well, this is not an unusual thing

sometimes the network gets stuck in a local optimum and then jumps out to find a better solution

**Comment by guanyonglai** [comment]
but It happens all the time,i set the evaluate frequence 20,and first epoch i evaluate the rank-1 is always: Rank-1  : 21.2%, is this a bug?

**Comment by KaiyangZhou** [comment]
the seeding turns the training into a deterministic mode

again, seeing a fluctuated performance is very normal during the course of DNN training (due to the nature of non-convex optimization), when it gets close to the end of training, the performance will typically become much stable when smaller lr is used

what you really care about is the final performance when the model *converges*

**Comment by guanyonglai** [comment]
soga
