### ISSUE TITLE
Dot product score for vectors belonging to different person is very high

### ISSUE THREAD

**Issue by kafan1986** [KaiyangZhou/deep-person-reid#384]
I trained the model for a lower resolution. Although the post training the mAP was around 70% and Rank1 accuracy around 85+%. 

The output of the model is strange. The cosine similarity score of vectors belonging to different person is very high around 0.99+. I am not sure what is the issue here. I know that I am supposed to calculate euclidean distance  but given high dimensionality. Euclidean and dot product output should be quite similar.

**Comment by KaiyangZhou** [comment]
Using cosine similarity is quite common and very useful so don't worry about that. It's actually easier to manage in practice using cosine similarity due to its fixed range, i.e. [-1, 1]. E.g., you wanna set a threshold.

For your case, you might want to dig deeper by checking more image examples. I'm unable to give more comments as I don't know the details.
