### ISSUE TITLE
HACNN trained on Market1501 - Different results by large margin - Expected behaviour?

### ISSUE THREAD

**Issue by jpainam** [KaiyangZhou/deep-person-reid#40]
HI!
I trained your `hacnn` architecture and ended up with 
```python
Rank-1  : 86.1%
Rank-5  : 94.7%
Rank-10 : 96.6%
Rank-20 : 97.8%
mAP: 67.3%
````
Which are different from the original results reported in the paper `91.2` for rank1 and `75.7` for mAP
Pls, I want to make sure that this is the expected result and that you are getting the same result.

Thanks

**Comment by gceboh** [comment]
#27

**Comment by SpONA** [comment]
may I have a look at your training settings on this result?

**Comment by jpainam** [comment]
I used the default settings for the most part except, a batch_size of 32. But This doesn't solve the problem and i suggest you to follow [this](https://github.com/KaiyangZhou/deep-person-reid/issues/27) issue to get better results

**Comment by SpONA** [comment]
Thank you so much. I have seen this as well. I will try to train with batch_size 32. Thanks~

----- 原始邮件 -----
发件人: "Jean-Paul AINAM" <notifications@github.com>
收件人: "KaiyangZhou/deep-person-reid" <deep-person-reid@noreply.github.com>
抄送: "SpONA" <spofnewage@sjtu.edu.cn>, "Comment" <comment@noreply.github.com>
发送时间: 星期日, 2018年 10 月 21日 下午 1:32:38
主题: Re: [KaiyangZhou/deep-person-reid] HACNN trained on Market1501 - Different results by large margin - Expected behaviour? (#40)

I used the default settings for the most part except, a batch_size of 32. But This doesn't solve the problem and i suggest you to follow [this](https://github.com/KaiyangZhou/deep-person-reid/issues/27) issue to get better results
