### ISSUE TITLE
Error met when trying to reproduce HACNN result (Python3)

### ISSUE THREAD

**Issue by lzhaozi** [KaiyangZhou/deep-person-reid#6]
I am trying to reproduce the HACNN result. I've downloaded CUHK03 dataset and process it as described in README. However, when I apply the train command of HACNN as described in README, I've met python error:
![hacnn](https://user-images.githubusercontent.com/6657346/39623956-fc9a4ff2-4fc9-11e8-9dc3-fbc077dc1107.jpg)
I am an beginner of ReID, I an running the repo in my personal bought AWS K80 GPU Ubuntu 16.04 LTS server, in which the Python is 3.6.4 in Anaconda3, and the torch 0.4.0, with torchvision 0.2.1:
![pythonenv](https://user-images.githubusercontent.com/6657346/39624228-0e2b9f22-4fcb-11e8-9f9a-5e967a5435a2.jpg)
Where is the problem do you think? Can you give me some hint, from the capture image above?
Thanks.

**Comment by lzhaozi** [comment]
This is my personal bought amazon aws K80 GPU information. And I only bought one K80 GPU, not four:
![gpu](https://user-images.githubusercontent.com/6657346/39624494-0f7be78c-4fcc-11e8-9524-9717cf9c8195.jpg)

**Comment by KaiyangZhou** [comment]
This error is caused by that the division `/` in python3 is a bit different from python2. I tried the following code in python3
```
import torch.nn as nn
a = 10
b = a / 2
conv = nn.Conv2d(a, b, 1)
```
and get the same error as yours. This is because `b=a/2` leads to a float number, which cannot be fed to the arguments of `nn.Conv2d()` as they must be integers.

This problem can be solved by changing `a = b/2` to `a=int(b/2)` for every line that uses division, e.g. [here](https://github.com/KaiyangZhou/deep-person-reid/blob/master/models/HACNN.py#L37). Sorry for the inconvenience. I have been using python2 so forgot to consider python3. Let me know if this way solves the problem.

**Comment by lzhaozi** [comment]
That does work. Now the HACNN training is converging. 
I've add int() to the LINE 37, 72, 118, 119 of HACNN.py. And the training is on-going now.
Thank you very much.

**Comment by KaiyangZhou** [comment]
You can use `a=b//2`, which is a more standard way. I will incorporate this later.

**Comment by liliangqi** [comment]
So, is this project based on Python 2.7?

**Comment by KaiyangZhou** [comment]
Yes. But it should work with python3.

Do you find anything incompatible with python3?

**Comment by liliangqi** [comment]
@KaiyangZhou Yes. It raised error "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 875: ordinal not in range(128)" when I load your trained model. I think it is because of pickle in Python2.
I have transformed your trained model to the Python3 format by steps below.

In Python2,
```python
checkpoint = torch.load("xxx.pth.tar")
with open("xxx.pkl", "wb") as f:
    pickle.dump(checkpointfile, f)
```

Then in Python3
```python
with open('saved-models/ckpt.pkl', 'rb') as f:
    data = pickle.load(f, encoding='bytes')

new_data = dict()
for key in data.keys():
    new_data[str(key, encoding='utf-8')] = data[key]

state_dict = new_data['state_dict']
new_state_dict = OrderedDict()

for key in state_dict.keys():
    new_state_dict[str(key, encoding='utf-8')] = state_dict[key]

new_data['state_dict'] = new_state_dict
torch.save(new_data, 'new.pth.tar')
```

And it would work with Python3 when using `torch.load('new.pth.tar')`
