### ISSUE TITLE
How does this project work for videos?

### ISSUE THREAD

**Issue by Pealing** [KaiyangZhou/deep-person-reid#97]
If I understand it correctly, the `VideoDataManager` in `train_vidreid_xent.py` uses `video_dataset_kwargs` to setup default parameters, where `image_training` is `True` by default. If that is the case, my concerns are as follows.

* Does it make any sense to train a model for videos based on individual frames?
* How does this project work for videos if only image-based models are provided, or do we need to provide our own video-based model?

Thanks.

**Comment by KaiyangZhou** [comment]
Regarding your first question:
- Video reid has more images for each person, thus containing richer information (e.g. pose).
- As reid models can be trained with classification loss (which turned out to work really well), it is natural to add more images for each identity to augment the sample size, i.e. using all images in a tracklet rather than randomly sampling one as did by image reid.
- Given a strong CNN architecture, robust features can be learned with simple image-based training. By average-pooling image features within tracklets, strong performance can be obtained (which can beat most complicated models). Here, by robust, I mean the learned CNN features are tolerant to noisy images in a tracklet, e.g. if you contaminate some images (even half) in a tracklet with random masks to simulate occlusion, the performance wouldn't drop significantly.
- In terms of real-world applications, using average pooling with a strong CNN model is efficient (e.g. store precomputed gallery features).

Regarding your second question:
- You can use this code to train video-reid models or implement your own algorithms based on this project. The purpose of releasing the pretrained models in the model zoo is to provide baseline models which people can use to do some research. They can also give a sense of what performance can be obtained by what kind of CNN architectures.

Hope this clarifies.

**Comment by gceboh** [comment]
https://github.com/KaiyangZhou/deep-person-reid/issues/87#issuecomment-446437639
